steps:
  - name: node:10.17.0
    entrypoint: yarn
    args: ["--cwd", "functions", "install"]
  - name: gcr.io/$PROJECT_ID/firebase
    args: ["deploy", "--only", "functions"]
    secretEnv: ['FIREBASE_TOKEN']
secrets:
  - kmsKeyName: 'projects/gatsby-contentful-firebase/locations/global/keyRings/cloudbuilder/cryptoKeys/firebase-token'
    secretEnv:
      FIREBASE_TOKEN: 'CiQAYE+xkpaPIzFJn2g3M0ktAfhJ+caD+JxjFmCkoE88lkAUUBcSkAEAjK7M0X1eCUTfqS6VqoLCU+HvdtebPbI5U/KM35o/pi1gY37BKfwJeCas5eIsNTK8B5qbIGDE9qKPJfxVEsMkbDKgPVd6LQyZBjxz84Fgz3/dcaZ5HycKGKsCYQYvJ/yKmBCH3/RH5haj2o+uYUDzq2HFlGOJ5c5N1DyYyYI0zlG1lC/zTApCZGFh7c1Xbjs='